-- Material 3 for Mantle. `local m3 = require("m3")` gives every component as `m3.<name>(id, opts)`,
-- plus `m3.theme` (live colour roles, type, motion), `m3.overlay` (snackbar, dialog, layers),
-- `m3.shapes` and `m3.app_window`. One component family per file: `require("m3.slider")` loads one.
-- See m3/README.md.
local overlay = require("m3.overlay")

return {
    theme = require("m3.theme"),
    overlay = overlay,
    shapes = require("m3.shapes"),
    app_window = overlay.app_window,
    -- Core
    merge = require("m3.core").merge,
    text = require("m3.core").text,
    icon = require("m3.core").icon,
    interactive = require("m3.core").interactive,
    -- Actions
    button = require("m3.button").button,
    icon_button = require("m3.icon_button").icon_button,
    fab = require("m3.fab").fab,
    extended_fab = require("m3.fab").extended_fab,
    fab_menu = require("m3.fab").fab_menu,
    button_group = require("m3.button_group").button_group,
    split_button = require("m3.split_button").split_button,
    segmented_button = require("m3.segmented_button").segmented_button,
    -- Communication
    badge = require("m3.badge").badge,
    badged = require("m3.badge").badged,
    linear_progress = require("m3.progress").linear_progress,
    circular_progress = require("m3.progress").circular_progress,
    loading_indicator = require("m3.loading_indicator").loading_indicator,
    shape = require("m3.loading_indicator").shape,
    tooltip = require("m3.tooltip").tooltip,
    rich_tooltip = require("m3.tooltip").rich_tooltip,
    -- Containment
    divider = require("m3.divider").divider,
    list_item = require("m3.list").list_item,
    list = require("m3.list").list,
    card = require("m3.card").card,
    carousel = require("m3.carousel").carousel,
    open_bottom_sheet = require("m3.sheet").open_bottom_sheet,
    open_side_sheet = require("m3.sheet").open_side_sheet,
    open_fullscreen_dialog = require("m3.sheet").open_fullscreen_dialog,
    -- Navigation
    tabs = require("m3.tabs").tabs,
    tab_content = require("m3.tabs").tab_content,
    navigation_bar = require("m3.navigation_bar").navigation_bar,
    navigation_drawer = require("m3.navigation_drawer").navigation_drawer,
    open_navigation_drawer = require("m3.navigation_drawer").open_navigation_drawer,
    navigation_rail = require("m3.navigation_rail").navigation_rail,
    top_app_bar_height = require("m3.top_app_bar").top_app_bar_height,
    top_app_bar = require("m3.top_app_bar").top_app_bar,
    toolbar = require("m3.toolbar").toolbar,
    -- Selection
    checkbox = require("m3.checkbox").checkbox,
    checkbox_group = require("m3.checkbox").checkbox_group,
    radio_group = require("m3.radio").radio_group,
    switch = require("m3.switch").switch,
    chip = require("m3.chips").chip,
    input_chips = require("m3.chips").input_chips,
    suggestion_chips = require("m3.chips").suggestion_chips,
    slider = require("m3.slider").slider,
    open_menu = require("m3.menu").open_menu,
    menu_open = require("m3.menu").menu_open,
    dropdown = require("m3.menu").dropdown,
    open_date_picker = require("m3.date_picker").open_date_picker,
    date_picker = require("m3.date_picker").date_picker,
    open_time_picker = require("m3.time_picker").open_time_picker,
    time_picker = require("m3.time_picker").time_picker,
    -- Text inputs
    text_field = require("m3.text_field").text_field,
    open_search_view = require("m3.search").open_search_view,
    search_bar = require("m3.search").search_bar,
}
