-- Material 3 for Mantle. `local m3 = require("m3")` gives every component as `m3.<name>(id, opts)`,
-- plus `m3.theme` (live colour roles, type, motion), `m3.overlay` (snackbar, dialog, layers),
-- `m3.shapes`, `m3.core` (set `m3.core.window` to the app window's id in a multi-window app) and
-- `m3.app_window`. One component family per file: `require("m3.selection.slider")`
-- loads one. See m3/README.md.
local window = require("m3.window")

return {
    theme = require("m3.theme"),
    overlay = require("m3.overlay"),
    shapes = require("m3.shapes"),
    core = require("m3.core"),
    -- Window (window.lua)
    app_window = window.app_window,
    window_controls = window.window_controls,
    window_drag = window.window_drag,
    window_class = window.window_class,
    -- Core (core.lua)
    scroll_ease = require("m3.core").scroll_ease,
    focusable = require("m3.core").focusable,
    merge = require("m3.core").merge,
    text = require("m3.core").text,
    icon = require("m3.core").icon,
    interactive = require("m3.core").interactive,
    -- Actions (actions/)
    button = require("m3.actions.button").button,
    icon_button = require("m3.actions.icon_button").icon_button,
    fab = require("m3.actions.fab").fab,
    extended_fab = require("m3.actions.fab").extended_fab,
    fab_menu = require("m3.actions.fab").fab_menu,
    button_group = require("m3.actions.button_group").button_group,
    split_button = require("m3.actions.split_button").split_button,
    segmented_button = require("m3.actions.segmented_button").segmented_button,
    -- Communication (communication/)
    badge = require("m3.communication.badge").badge,
    badged = require("m3.communication.badge").badged,
    linear_progress = require("m3.communication.progress").linear_progress,
    circular_progress = require("m3.communication.progress").circular_progress,
    loading_indicator = require("m3.communication.loading_indicator").loading_indicator,
    shape = require("m3.communication.loading_indicator").shape,
    tooltip = require("m3.communication.tooltip").tooltip,
    rich_tooltip = require("m3.communication.tooltip").rich_tooltip,
    -- Containment (containment/)
    divider = require("m3.containment.divider").divider,
    list_item = require("m3.containment.list").list_item,
    item_list = require("m3.containment.list").item_list,
    list = require("m3.containment.list").list,
    card = require("m3.containment.card").card,
    carousel = require("m3.containment.carousel").carousel,
    open_bottom_sheet = require("m3.containment.sheet").open_bottom_sheet,
    open_side_sheet = require("m3.containment.sheet").open_side_sheet,
    open_fullscreen_dialog = require("m3.containment.sheet").open_fullscreen_dialog,
    -- Layout (layout/): follows the window size class
    adaptive_navigation = require("m3.layout.adaptive").adaptive_navigation,
    list_detail = require("m3.layout.adaptive").list_detail,
    -- Navigation (navigation/)
    tabs = require("m3.navigation.tabs").tabs,
    tab_content = require("m3.navigation.tabs").tab_content,
    navigation_bar = require("m3.navigation.navigation_bar").navigation_bar,
    navigation_drawer = require("m3.navigation.navigation_drawer").navigation_drawer,
    open_navigation_drawer = require("m3.navigation.navigation_drawer").open_navigation_drawer,
    navigation_rail = require("m3.navigation.navigation_rail").navigation_rail,
    fade_through = require("m3.navigation.fade_through").fade_through,
    top_app_bar_height = require("m3.navigation.top_app_bar").top_app_bar_height,
    top_app_bar = require("m3.navigation.top_app_bar").top_app_bar,
    toolbar = require("m3.navigation.toolbar").toolbar,
    -- Selection (selection/)
    checkbox = require("m3.selection.checkbox").checkbox,
    checkbox_group = require("m3.selection.checkbox").checkbox_group,
    radio_group = require("m3.selection.radio").radio_group,
    switch = require("m3.selection.switch").switch,
    chip = require("m3.selection.chips").chip,
    chip_group = require("m3.selection.chips").chip_group,
    input_chips = require("m3.selection.chips").input_chips,
    suggestion_chips = require("m3.selection.chips").suggestion_chips,
    slider = require("m3.selection.slider").slider,
    open_menu = require("m3.selection.menu").open_menu,
    menu_open = require("m3.selection.menu").menu_open,
    context_menu = require("m3.selection.menu").context_menu,
    bind_shortcuts = require("m3.selection.menu").bind_shortcuts,
    menu_highlighted = require("m3.selection.menu").highlighted,
    pick_highlighted = require("m3.selection.menu").pick_highlighted,
    dropdown = require("m3.selection.menu").dropdown,
    open_date_picker = require("m3.selection.date_picker").open_date_picker,
    date_picker = require("m3.selection.date_picker").date_picker,
    open_time_picker = require("m3.selection.time_picker").open_time_picker,
    time_picker = require("m3.selection.time_picker").time_picker,
    -- Inputs (inputs/)
    text_field = require("m3.inputs.text_field").text_field,
    edit_click = require("m3.inputs.text_field").edit_click, -- right-click Edit menu helper
    open_search_view = require("m3.inputs.search").open_search_view,
    search_bar = require("m3.inputs.search").search_bar,
}
